"""
Catalogue of the 15 demonstration queries (Q1-Q15).

The same list drives:
  * the Reports page of the web app (each query shows its SQL + result)
  * db/09_queries.sql  (generated by  python backend/export_queries.py)

Parameters use psycopg's named style: %(name)s
"""

QUERIES = [
    {
        "id": "Q1", "concept": "INNER JOIN (5 tables)",
        "title": "Order lines with product category and seller city",
        "params": {"state": "SP", "limit": 50},
        "sql": """
SELECT o.order_id, o.purchase_ts::date AS purchased, o.order_status,
       c.category_name_en AS category, oi.price, oi.freight_value,
       sz.city AS seller_city, sz.state_code AS seller_state
FROM orders o
JOIN order_item oi ON oi.order_id = o.order_id
JOIN product p     ON p.product_id = oi.product_id
JOIN category c    ON c.category_name = p.category_name
JOIN seller s      ON s.seller_id = oi.seller_id
JOIN zip_code sz   ON sz.zip_prefix = s.zip_prefix
WHERE sz.state_code = %(state)s
ORDER BY o.purchase_ts DESC
LIMIT %(limit)s""",
    },
    {
        "id": "Q2", "concept": "LEFT JOIN + IS NULL (anti-join)",
        "title": "Delivered orders that never received a review",
        "params": {"limit": 50},
        "sql": """
SELECT o.order_id, o.purchase_ts::date AS purchased, o.delivered_customer_date::date AS delivered
FROM orders o
LEFT JOIN review r ON r.order_id = o.order_id
WHERE r.order_id IS NULL
  AND o.order_status = 'delivered'
ORDER BY o.purchase_ts DESC
LIMIT %(limit)s""",
    },
    {
        "id": "Q3", "concept": "SELF JOIN",
        "title": "Category pairs bought together in the same order",
        "params": {"limit": 20},
        "sql": """
SELECT c1.category_name_en AS category_a, c2.category_name_en AS category_b,
       COUNT(DISTINCT a.order_id) AS orders_together
FROM order_item a
JOIN order_item b ON b.order_id = a.order_id AND b.order_item_id > a.order_item_id
JOIN product pa   ON pa.product_id = a.product_id
JOIN product pb   ON pb.product_id = b.product_id
JOIN category c1  ON c1.category_name = pa.category_name
JOIN category c2  ON c2.category_name = pb.category_name
WHERE pa.category_name < pb.category_name
GROUP BY c1.category_name_en, c2.category_name_en
ORDER BY orders_together DESC
LIMIT %(limit)s""",
    },
    {
        "id": "Q4", "concept": "Aggregates + GROUP BY",
        "title": "Monthly orders, revenue and average ticket",
        "params": {},
        "sql": """
SELECT to_char(date_trunc('month', o.purchase_ts), 'YYYY-MM') AS month,
       COUNT(DISTINCT o.order_id)                  AS orders,
       ROUND(SUM(oi.price), 2)                     AS revenue,
       ROUND(SUM(oi.price) / COUNT(DISTINCT o.order_id), 2) AS avg_ticket,
       ROUND(AVG(oi.freight_value), 2)             AS avg_freight
FROM orders o
JOIN order_item oi ON oi.order_id = o.order_id
WHERE o.order_status NOT IN ('canceled', 'unavailable')
GROUP BY 1
ORDER BY 1""",
    },
    {
        "id": "Q5", "concept": "GROUP BY + HAVING",
        "title": "Busy sellers with poor ratings",
        "params": {"min_orders": 50, "max_rating": 3.8},
        "sql": """
SELECT s.seller_id, z.city, z.state_code,
       COUNT(DISTINCT oi.order_id)    AS orders,
       ROUND(AVG(r.review_score), 2)  AS avg_rating
FROM seller s
JOIN zip_code z    ON z.zip_prefix = s.zip_prefix
JOIN order_item oi ON oi.seller_id = s.seller_id
JOIN review r      ON r.order_id = oi.order_id
GROUP BY s.seller_id, z.city, z.state_code
HAVING COUNT(DISTINCT oi.order_id) > %(min_orders)s
   AND AVG(r.review_score) < %(max_rating)s
ORDER BY avg_rating""",
    },
    {
        "id": "Q6", "concept": "Subquery with IN",
        "title": "Customers who bought from the #1 revenue category",
        "params": {"limit": 50},
        "sql": """
SELECT ca.customer_unique_id, z.city, z.state_code
FROM customer_account ca
JOIN zip_code z ON z.zip_prefix = ca.zip_prefix
WHERE ca.customer_id IN (
    SELECT o.customer_id
    FROM orders o
    JOIN order_item oi ON oi.order_id = o.order_id
    JOIN product p     ON p.product_id = oi.product_id
    WHERE p.category_name = (
        SELECT p2.category_name
        FROM order_item oi2 JOIN product p2 ON p2.product_id = oi2.product_id
        WHERE p2.category_name IS NOT NULL
        GROUP BY p2.category_name
        ORDER BY SUM(oi2.price) DESC
        LIMIT 1))
LIMIT %(limit)s""",
    },
    {
        "id": "Q7", "concept": "Correlated subqueries (in WHERE and SELECT)",
        "title": "Loyal customers: people with 3 or more orders and their total spend",
        "params": {"min_orders": 3},
        "sql": """
SELECT c.customer_unique_id,
       (SELECT COUNT(*) FROM customer_account ca
         WHERE ca.customer_unique_id = c.customer_unique_id)             AS orders,
       (SELECT ROUND(SUM(oi.price + oi.freight_value), 2)
          FROM customer_account ca
          JOIN orders o      ON o.customer_id = ca.customer_id
          JOIN order_item oi ON oi.order_id = o.order_id
         WHERE ca.customer_unique_id = c.customer_unique_id)             AS total_spend
FROM customer c
WHERE (SELECT COUNT(*) FROM customer_account ca
        WHERE ca.customer_unique_id = c.customer_unique_id) >= %(min_orders)s   -- correlated on c
ORDER BY orders DESC, total_spend DESC""",
    },
    {
        "id": "Q8", "concept": "EXISTS / NOT EXISTS",
        "title": "Sellers with at least one 1-star review but no canceled orders",
        "params": {"limit": 50},
        "sql": """
SELECT s.seller_id, fn_seller_rating(s.seller_id) AS avg_rating
FROM seller s
WHERE EXISTS (SELECT 1 FROM order_item oi JOIN review r ON r.order_id = oi.order_id
              WHERE oi.seller_id = s.seller_id AND r.review_score = 1)
  AND NOT EXISTS (SELECT 1 FROM order_item oi JOIN orders o ON o.order_id = oi.order_id
                  WHERE oi.seller_id = s.seller_id AND o.order_status = 'canceled')
ORDER BY avg_rating
LIMIT %(limit)s""",
    },
    {
        "id": "Q9", "concept": "Derived table (subquery in FROM)",
        "title": "States whose average delivery time beats the national average",
        "params": {},
        "sql": """
SELECT t.state_code, t.orders, t.avg_days,
       ROUND((SELECT AVG(EXTRACT(EPOCH FROM delivered_customer_date - purchase_ts) / 86400)
                FROM orders WHERE delivered_customer_date IS NOT NULL), 1) AS national_avg
FROM (
    SELECT z.state_code, COUNT(*) AS orders,
           ROUND(AVG(EXTRACT(EPOCH FROM o.delivered_customer_date - o.purchase_ts) / 86400), 1) AS avg_days
    FROM orders o
    JOIN customer_account ca ON ca.customer_id = o.customer_id
    JOIN zip_code z          ON z.zip_prefix = ca.zip_prefix
    WHERE o.delivered_customer_date IS NOT NULL
    GROUP BY z.state_code
) t
WHERE t.avg_days < (SELECT AVG(EXTRACT(EPOCH FROM delivered_customer_date - purchase_ts) / 86400)
                      FROM orders WHERE delivered_customer_date IS NOT NULL)
ORDER BY t.avg_days""",
    },
    {
        "id": "Q10", "concept": "Scalar subqueries in SELECT + stored function",
        "title": "Orders with item count, order total and amount paid",
        "params": {"limit": 50},
        "sql": """
SELECT o.order_id, o.order_status,
       (SELECT COUNT(*) FROM order_item oi WHERE oi.order_id = o.order_id) AS items,
       fn_order_total(o.order_id)                                          AS order_total,
       (SELECT SUM(payment_value) FROM payment p WHERE p.order_id = o.order_id) AS paid
FROM orders o
ORDER BY o.purchase_ts DESC
LIMIT %(limit)s""",
    },
    {
        "id": "Q11", "concept": "UNION / INTERSECT / EXCEPT",
        "title": "Which states have customers, sellers, or both",
        "params": {},
        "sql": """
(SELECT z.state_code, 'customers and sellers' AS presence
   FROM customer_account ca JOIN zip_code z ON z.zip_prefix = ca.zip_prefix
 INTERSECT
 SELECT z.state_code, 'customers and sellers'
   FROM seller s JOIN zip_code z ON z.zip_prefix = s.zip_prefix)
UNION ALL
(SELECT z.state_code, 'customers only'
   FROM customer_account ca JOIN zip_code z ON z.zip_prefix = ca.zip_prefix
 EXCEPT
 SELECT z.state_code, 'customers only'
   FROM seller s JOIN zip_code z ON z.zip_prefix = s.zip_prefix)
ORDER BY presence, state_code""",
    },
    {
        "id": "Q12", "concept": "CASE inside aggregates",
        "title": "On-time vs late deliveries and rating by customer state",
        "params": {},
        "sql": """
SELECT z.state_code,
       COUNT(*) AS delivered,
       SUM(CASE WHEN o.delivered_customer_date <= o.estimated_delivery_date THEN 1 ELSE 0 END) AS on_time,
       SUM(CASE WHEN o.delivered_customer_date >  o.estimated_delivery_date THEN 1 ELSE 0 END) AS late,
       ROUND(100.0 * AVG(CASE WHEN o.delivered_customer_date > o.estimated_delivery_date
                              THEN 1 ELSE 0 END), 1) AS late_pct,
       ROUND(AVG(r.review_score), 2) AS avg_rating
FROM orders o
JOIN customer_account ca ON ca.customer_id = o.customer_id
JOIN zip_code z          ON z.zip_prefix = ca.zip_prefix
LEFT JOIN review r       ON r.order_id = o.order_id
WHERE o.delivered_customer_date IS NOT NULL
GROUP BY z.state_code
ORDER BY late_pct DESC""",
    },
    {
        "id": "Q13", "concept": "Window functions (LAG, running SUM, RANK)",
        "title": "Month-over-month revenue growth, running total and rank",
        "params": {},
        "sql": """
WITH monthly AS (
    SELECT date_trunc('month', o.purchase_ts)::date AS month, SUM(oi.price) AS revenue
    FROM orders o JOIN order_item oi ON oi.order_id = o.order_id
    WHERE o.purchase_ts >= '2017-01-01' AND o.purchase_ts < '2018-09-01'
    GROUP BY 1
)
SELECT to_char(month, 'YYYY-MM') AS month,
       ROUND(revenue, 0) AS revenue,
       ROUND(100.0 * (revenue - LAG(revenue) OVER (ORDER BY month))
             / LAG(revenue) OVER (ORDER BY month), 1)            AS growth_pct,
       ROUND(SUM(revenue) OVER (ORDER BY month), 0)              AS running_total,
       RANK() OVER (ORDER BY revenue DESC)                       AS revenue_rank
FROM monthly
ORDER BY month""",
    },
    {
        "id": "Q13b", "concept": "Window function: RANK() OVER (PARTITION BY ...)",
        "title": "Top 3 best-selling products in each of the 5 biggest categories",
        "params": {},
        "sql": """
WITH sales AS (
    SELECT c.category_name_en AS category, oi.product_id,
           COUNT(*) AS units, ROUND(SUM(oi.price), 2) AS revenue
    FROM order_item oi
    JOIN product p  ON p.product_id = oi.product_id
    JOIN category c ON c.category_name = p.category_name
    GROUP BY c.category_name_en, oi.product_id
), ranked AS (
    SELECT *, RANK() OVER (PARTITION BY category ORDER BY units DESC) AS rank_in_category,
           SUM(units) OVER (PARTITION BY category) AS category_units
    FROM sales
)
SELECT category, rank_in_category, product_id, units, revenue
FROM ranked
WHERE rank_in_category <= 3
  AND category IN (SELECT category FROM sales GROUP BY category ORDER BY SUM(units) DESC LIMIT 5)
ORDER BY category, rank_in_category""",
    },
    {
        "id": "Q14", "concept": "CTE + recursive CTE",
        "title": "Customer lifetime value with every month of 2017 (zero-sale months included)",
        "params": {},
        "sql": """
WITH RECURSIVE months(m) AS (
    SELECT DATE '2017-01-01'
    UNION ALL
    SELECT (m + INTERVAL '1 month')::date FROM months WHERE m < DATE '2017-12-01'
), clv AS (
    SELECT ca.customer_unique_id,
           COUNT(DISTINCT o.order_id) AS orders,
           SUM(oi.price + oi.freight_value) AS lifetime_value,
           MIN(date_trunc('month', o.purchase_ts))::date AS first_month
    FROM customer_account ca
    JOIN orders o      ON o.customer_id = ca.customer_id
    JOIN order_item oi ON oi.order_id = o.order_id
    GROUP BY ca.customer_unique_id
)
SELECT to_char(months.m, 'YYYY-MM') AS month,
       COUNT(clv.customer_unique_id)            AS new_customers,
       ROUND(COALESCE(AVG(clv.lifetime_value), 0), 2) AS avg_lifetime_value,
       COALESCE(SUM(CASE WHEN clv.orders > 1 THEN 1 ELSE 0 END), 0) AS repeat_customers
FROM months
LEFT JOIN clv ON clv.first_month = months.m
GROUP BY months.m
ORDER BY months.m""",
    },
    {
        "id": "Q15", "concept": "ALL / ANY",
        "title": "Products heavier than every telephony product",
        "params": {"limit": 50},
        "sql": """
SELECT p.product_id, c.category_name_en AS category, p.weight_g
FROM product p
JOIN category c ON c.category_name = p.category_name
WHERE p.weight_g > ALL (SELECT weight_g FROM product
                        WHERE category_name = 'telefonia' AND weight_g IS NOT NULL)
ORDER BY p.weight_g DESC
LIMIT %(limit)s""",
    },
    {
        "id": "Q16", "concept": "Full-text search (GIN index)",
        "title": "Reviews mentioning a word (Portuguese stemming)",
        "params": {"word": "atraso", "limit": 50},
        "sql": """
SELECT r.order_id, r.review_score, r.comment_title, r.comment_message
FROM review r
WHERE to_tsvector('portuguese', coalesce(r.comment_title,'') || ' ' || coalesce(r.comment_message,''))
      @@ plainto_tsquery('portuguese', %(word)s)
ORDER BY r.creation_date DESC
LIMIT %(limit)s""",
    },
]

QUERY_BY_ID = {q["id"]: q for q in QUERIES}
