"""
Catalogue of the 15 demonstration queries (Q1-Q15).

The same list drives:
  * the Reports page of the web app (each query shows its SQL + result)
  * db/09_queries.sql  (generated by  python backend/export_queries.py)

Parameters use psycopg's named style: %(name)s
"""

QUERIES = [
    {
        "id": "Q1", "concept": "INNER JOIN (5 tables)",
        "title": "Order lines with product category and seller city",
        "params": {"state": "SP", "limit": 50},
        "sql": """
SELECT o.order_id, o.purchase_ts::date AS purchased, o.order_status,
       c.category_name_en AS category, oi.price, oi.freight_value,
       sz.city AS seller_city, sz.state_code AS seller_state
FROM orders o
JOIN order_item oi ON oi.order_id = o.order_id
JOIN product p     ON p.product_id = oi.product_id
JOIN category c    ON c.category_name = p.category_name
JOIN seller s      ON s.seller_id = oi.seller_id
JOIN zip_code sz   ON sz.zip_prefix = s.zip_prefix
WHERE sz.state_code = %(state)s
ORDER BY o.purchase_ts DESC
LIMIT %(limit)s""",
    },
    {
        "id": "Q2", "concept": "LEFT JOIN + IS NULL (anti-join)",
        "title": "Delivered orders that never received a review",
        "params": {"limit": 50},
        "sql": """
SELECT o.order_id, o.purchase_ts::date AS purchased, o.delivered_customer_date::date AS delivered
FROM orders o
LEFT JOIN review r ON r.order_id = o.order_id
WHERE r.order_id IS NULL
  AND o.order_status = 'delivered'
ORDER BY o.purchase_ts DESC
LIMIT %(limit)s""",
    },
    {
        "id": "Q3", "concept": "SELF JOIN",
        "title": "Category pairs bought together in the same order",
        "params": {"limit": 20},
        "sql": """
SELECT c1.category_name_en AS category_a, c2.category_name_en AS category_b,
       COUNT(DISTINCT a.order_id) AS orders_together
FROM order_item a
JOIN order_item b ON b.order_id = a.order_id AND b.order_item_id > a.order_item_id
JOIN product pa   ON pa.product_id = a.product_id
JOIN product pb   ON pb.product_id = b.product_id
JOIN category c1  ON c1.category_name = pa.category_name
JOIN category c2  ON c2.category_name = pb.category_name
WHERE pa.category_name < pb.category_name
GROUP BY c1.category_name_en, c2.category_name_en
ORDER BY orders_together DESC
LIMIT %(limit)s""",
    },
    {
        "id": "Q4", "concept": "Aggregates + GROUP BY",
        "title": "Monthly orders, revenue and average ticket",
        "params": {},
        "sql": """
SELECT to_char(date_trunc('month', o.purchase_ts), 'YYYY-MM') AS month,
       COUNT(DISTINCT o.order_id)                  AS orders,
       ROUND(SUM(oi.price), 2)                     AS revenue,
       ROUND(SUM(oi.price) / COUNT(DISTINCT o.order_id), 2) AS avg_ticket,
       ROUND(AVG(oi.freight_value), 2)             AS avg_freight
FROM orders o
JOIN order_item oi ON oi.order_id = o.order_id
WHERE o.order_status NOT IN ('canceled', 'unavailable')
GROUP BY 1
ORDER BY 1""",
    },
    {
        "id": "Q5", "concept": "GROUP BY + HAVING",
        "title": "Busy sellers with poor ratings",
        "params": {"min_orders": 50, "max_rating": 3.8},
        "sql": """
SELECT s.seller_id, z.city, z.state_code,
       COUNT(DISTINCT oi.order_id)    AS orders,
       ROUND(AVG(r.review_score), 2)  AS avg_rating
FROM seller s
JOIN zip_code z    ON z.zip_prefix = s.zip_prefix
JOIN order_item oi ON oi.seller_id = s.seller_id
JOIN review r      ON r.order_id = oi.order_id
GROUP BY s.seller_id, z.city, z.state_code
HAVING COUNT(DISTINCT oi.order_id) > %(min_orders)s
   AND AVG(r.review_score) < %(max_rating)s
ORDER BY avg_rating""",
    },
    {
        "id": "Q6", "concept": "Subquery with IN",
        "title": "Customers who bought from the #1 revenue category",
        "params": {"limit": 50},
        "sql": """
SELECT ca.customer_unique_id, z.city, z.state_code
FROM customer_account ca
JOIN zip_code z ON z.zip_prefix = ca.zip_prefix
WHERE ca.customer_id IN (
    SELECT o.customer_id
    FROM orders o
    JOIN order_item oi ON oi.order_id = o.order_id
    JOIN product p     ON p.product_id = oi.product_id
    WHERE p.category_name = (
        SELECT p2.category_name
        FROM order_item oi2 JOIN product p2 ON p2.product_id = oi2.product_id
        WHERE p2.category_name IS NOT NULL
        GROUP BY p2.category_name
        ORDER BY SUM(oi2.price) DESC
        LIMIT 1))
LIMIT %(limit)s""",
    },
    {
        "id": "Q7", "concept": "Correlated subqueries (in WHERE and SELECT)",
        "title": "Loyal customers: people with 3 or more orders and their total spend",
        "params": {"min_orders": 3},
        "sql": """
SELECT c.customer_unique_id,
       (SELECT COUNT(*) FROM customer_account ca
         WHERE ca.customer_unique_id = c.customer_unique_id)             AS orders,
       (SELECT ROUND(SUM(oi.price + oi.freight_value), 2)
          FROM customer_account ca
          JOIN orders o      ON o.customer_id = ca.customer_id
          JOIN order_item oi ON oi.order_id = o.order_id
         WHERE ca.customer_unique_id = c.customer_unique_id)             AS total_spend
FROM customer c
WHERE (SELECT COUNT(*) FROM customer_account ca
        WHERE ca.customer_unique_id = c.customer_unique_id) >= %(min_orders)s   -- correlated on c
ORDER BY orders DESC, total_spend DESC""",
    },
    {
        "id": "Q8", "concept": "EXISTS / NOT EXISTS",
        "title": "Sellers with at least one 1-star review but no canceled orders",
        "params": {"limit": 50},
        "sql": """
SELECT s.seller_id, fn_seller_rating(s.seller_id) AS avg_rating
FROM seller s
WHERE EXISTS (SELECT 1 FROM order_item oi JOIN review r ON r.order_id = oi.order_id
              WHERE oi.seller_id = s.seller_id AND r.review_score = 1)
  AND NOT EXISTS (SELECT 1 FROM order_item oi JOIN orders o ON o.order_id = oi.order_id
                  WHERE oi.seller_id = s.seller_id AND o.order_status = 'canceled')
ORDER BY avg_rating
LIMIT %(limit)s""",
    },
]
